services:
  cache:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #      - "6372:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ""
    networks:
      - questbucket-network
    volumes:
      - cache:/data
  database:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=questbucket
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    # ports:
    #   - "5432:5432"
    networks:
      - questbucket-network
    volumes:
      - db:/var/lib/postgresql/data
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - cache
    networks:
      - questbucket-network
    env_file:
      - .env
networks:
  questbucket-network:
    driver: bridge

volumes:
  cache:
    driver: local
  db:
