services:
  web:
    build:
      context: .
    ports:
      - "6996:6996"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - questbucket-network
    env_file:
      - .env
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=note
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    networks:
      - questbucket-network
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d aether"]
      interval: 3s
      timeout: 3s
      retries: 5
networks:
  questbucket-network:
    driver: bridge
volumes:
  db:
