services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - cache
    networks:
      - questbucket-network
    env_file:
      - .env
  cache:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #      - "6372:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ""
    networks:
      - questbucket-network
    volumes:
      - cache:/data
networks:
  questbucket-network:
    driver: bridge

volumes:
  cache:
    driver: local
